# File preprocessing notebook
This notebook aim to apply some cleaning and filters for future data analysis operations

## First step : Importation of pandas library and creation of the dataframe

In [1]:
import pandas as pd
import json

In [2]:
df = pd.read_csv('mapstr.csv')

In [3]:
df

,name,address,icon,userComment,tags
0,Barrio Meshica,"15 Rue de la Villette, 75019 Paris, France",restaurant,NaN,💸💸#Hispanique#TheFork 🍴
1,Mile Time,"Baquerizo Moreno E7-70, Quito, Ecuador",restaurant,🇹🇼,💸#Asiat#Vege/Vegan 🌱
2,Chifa Fuzhao (Chifa Fu Zhao),"Avenida 6 de Diciembre, N25-23, 170524 Quito, ...",restaurant,🇨🇳,💸#Asiat
3,Fairuz Café Restaurante / Shawarma Show,"Avenida 6 de Diciembre, N25-23, 170524 Quito, ...",restaurant,NaN,💸#Libanais 🇱🇧
4,Sant Just,"Calle 16A 2-73, 111711 Bogotá, D.C., Colombia",restaurant,NaN,💸💸#Viande#Restaurant
...,...,...,...,...,...
829,O'Cheese Naans,"20 Rue Pablo Neruda, 77200 Torcy, France",restaurant,NaN,Burger 🍔🍟#Grec 🥙#💸#À faire
830,Broadway Coffee,"4 Boulevard Carnot, 93250 Villemomble, France",fastfood,NaN,💸#Burger 🍔🍟#À faire
831,Mamagaya,24 Avenue Henri Barbusse 93700 Drancy France,restaurant,NaN,💸#Grec 🥙#Pâtes 🍝#À faire
832,La Maison Du Tacos,"23 Rue Saint-Spire, 91100 Corbeil-Essonnes, Fr...",restaurant,Meilleur endroit pour prendre un tacos FR . 🖕🏾...,💸#Halal#Tacos 🇫🇷#Validé ✅
833,French Cantine,"65 Avenue Gambetta, 93170 Bagnolet, France",restaurant,Meilleur sandwich que j’ai mangé. Les plats de...,💸#Grec 🥙#Halal#Pâtes 🍝#Validé ✅

## Second step : Filtering out the Private addresses, replacing the NaN values for comments to empty string and desc ordering to have the oldests addresses first

In [3]:
privateless_df = df[~df['tags'].str.contains("Private")]

In [4]:
privateless_df.loc[:,'userComment'] = privateless_df['userComment'].fillna("")

In [5]:
privateless_df

,name,address,icon,userComment,tags
0,Barrio Meshica,"15 Rue de la Villette, 75019 Paris, France",restaurant,,💸💸#Hispanique#TheFork 🍴
1,Mile Time,"Baquerizo Moreno E7-70, Quito, Ecuador",restaurant,🇹🇼,💸#Asiat#Vege/Vegan 🌱
2,Chifa Fuzhao (Chifa Fu Zhao),"Avenida 6 de Diciembre, N25-23, 170524 Quito, ...",restaurant,🇨🇳,💸#Asiat
3,Fairuz Café Restaurante / Shawarma Show,"Avenida 6 de Diciembre, N25-23, 170524 Quito, ...",restaurant,,💸#Libanais 🇱🇧
4,Sant Just,"Calle 16A 2-73, 111711 Bogotá, D.C., Colombia",restaurant,,💸💸#Viande#Restaurant
...,...,...,...,...,...
829,O'Cheese Naans,"20 Rue Pablo Neruda, 77200 Torcy, France",restaurant,,Burger 🍔🍟#Grec 🥙#💸#À faire
830,Broadway Coffee,"4 Boulevard Carnot, 93250 Villemomble, France",fastfood,,💸#Burger 🍔🍟#À faire
831,Mamagaya,24 Avenue Henri Barbusse 93700 Drancy France,restaurant,,💸#Grec 🥙#Pâtes 🍝#À faire
832,La Maison Du Tacos,"23 Rue Saint-Spire, 91100 Corbeil-Essonnes, Fr...",restaurant,Meilleur endroit pour prendre un tacos FR . 🖕🏾...,💸#Halal#Tacos 🇫🇷#Validé ✅
833,French Cantine,"65 Avenue Gambetta, 93170 Bagnolet, France",restaurant,Meilleur sandwich que j’ai mangé. Les plats de...,💸#Grec 🥙#Halal#Pâtes 🍝#Validé ✅

In [6]:
privateless_df = privateless_df.iloc[::-1]

In [7]:
privateless_df = privateless_df.reset_index(drop=True)

In [7]:
privateless_df

,name,address,icon,userComment,tags
0,French Cantine,"65 Avenue Gambetta, 93170 Bagnolet, France",restaurant,Meilleur sandwich que j’ai mangé. Les plats de...,💸#Grec 🥙#Halal#Pâtes 🍝#Validé ✅
1,La Maison Du Tacos,"23 Rue Saint-Spire, 91100 Corbeil-Essonnes, Fr...",restaurant,Meilleur endroit pour prendre un tacos FR . 🖕🏾...,💸#Halal#Tacos 🇫🇷#Validé ✅
2,Mamagaya,24 Avenue Henri Barbusse 93700 Drancy France,restaurant,,💸#Grec 🥙#Pâtes 🍝#À faire
3,Broadway Coffee,"4 Boulevard Carnot, 93250 Villemomble, France",fastfood,,💸#Burger 🍔🍟#À faire
4,O'Cheese Naans,"20 Rue Pablo Neruda, 77200 Torcy, France",restaurant,,Burger 🍔🍟#Grec 🥙#💸#À faire
...,...,...,...,...,...
807,Sant Just,"Calle 16A 2-73, 111711 Bogotá, D.C., Colombia",restaurant,,💸💸#Viande#Restaurant
808,Fairuz Café Restaurante / Shawarma Show,"Avenida 6 de Diciembre, N25-23, 170524 Quito, ...",restaurant,,💸#Libanais 🇱🇧
809,Chifa Fuzhao (Chifa Fu Zhao),"Avenida 6 de Diciembre, N25-23, 170524 Quito, ...",restaurant,🇨🇳,💸#Asiat
810,Mile Time,"Baquerizo Moreno E7-70, Quito, Ecuador",restaurant,🇹🇼,💸#Asiat#Vege/Vegan 🌱
811,Barrio Meshica,"15 Rue de la Villette, 75019 Paris, France",restaurant,,💸💸#Hispanique#TheFork 🍴

# Tags separations

## Columns split based on the # character

In [8]:
df_tags_columns = privateless_df['tags'].str.split('#', expand=True)

## Columns renamed based on the max number of tags

In [9]:
df_tags_columns.columns = [f'tag{i+1}' for i in range(df_tags_columns.shape[1])]

In [10]:
df_tags_columns

          tag1         tag2          tag3      tag4      tag5  tag6  tag7
0            💸       Grec 🥙         Halal   Pâtes 🍝  Validé ✅  None  None
1            💸        Halal      Tacos 🇫🇷  Validé ✅      None  None  None
2            💸       Grec 🥙       Pâtes 🍝   À faire      None  None  None
3            💸    Burger 🍔🍟       À faire      None      None  None  None
4    Burger 🍔🍟       Grec 🥙             💸   À faire      None  None  None
..         ...          ...           ...       ...       ...   ...   ...
807         💸💸       Viande    Restaurant      None      None  None  None
808          💸  Libanais 🇱🇧          None      None      None  None  None
809          💸        Asiat          None      None      None  None  None
810          💸        Asiat  Vege/Vegan 🌱      None      None  None  None
811         💸💸   Hispanique     TheFork 🍴      None      None  None  None

[812 rows x 7 columns]

## Concatenation of the tags columns with the original dataframe

In [10]:
privateless_df = pd.concat([privateless_df, df_tags_columns], axis=1)

In [11]:
privateless_df = privateless_df.drop("tags", axis=1)

In [15]:
import geopy

In [43]:
geolocator = geopy.Nominatim(user_agent="geoapi")
def get_address_info(address_name:str):
    location = geolocator.geocode(address_name)
    if location:
        elements = location.address.split(',')
        if len(elements) < 6:
            print(elements)
            pass
        return elements[-5].strip(), elements[-2].strip(), elements[-1].strip()

In [44]:
privateless_df['city'], privateless_df['postalCode'],privateless_df['country'] = zip(*privateless_df['address'].apply(get_address_info))

['Paris', ' Île-de-France', ' France métropolitaine', ' France']

IndexError: list index out of range

In [38]:
privateless_df

,name,address,icon,userComment,tag1,tag2,tag3,tag4,tag5,tag6,tag7
0,French Cantine,"65 Avenue Gambetta, 93170 Bagnolet, France",restaurant,Meilleur sandwich que j’ai mangé. Les plats de...,💸,Grec 🥙,Halal,Pâtes 🍝,Validé ✅,None,None
1,La Maison Du Tacos,"23 Rue Saint-Spire, 91100 Corbeil-Essonnes, Fr...",restaurant,Meilleur endroit pour prendre un tacos FR . 🖕🏾...,💸,Halal,Tacos 🇫🇷,Validé ✅,None,None,None
2,Mamagaya,24 Avenue Henri Barbusse 93700 Drancy France,restaurant,,💸,Grec 🥙,Pâtes 🍝,À faire,None,None,None
3,Broadway Coffee,"4 Boulevard Carnot, 93250 Villemomble, France",fastfood,,💸,Burger 🍔🍟,À faire,None,None,None,None
4,O'Cheese Naans,"20 Rue Pablo Neruda, 77200 Torcy, France",restaurant,,Burger 🍔🍟,Grec 🥙,💸,À faire,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...
807,Sant Just,"Calle 16A 2-73, 111711 Bogotá, D.C., Colombia",restaurant,,💸💸,Viande,Restaurant,None,None,None,None
808,Fairuz Café Restaurante / Shawarma Show,"Avenida 6 de Diciembre, N25-23, 170524 Quito, ...",restaurant,,💸,Libanais 🇱🇧,None,None,None,None,None
809,Chifa Fuzhao (Chifa Fu Zhao),"Avenida 6 de Diciembre, N25-23, 170524 Quito, ...",restaurant,🇨🇳,💸,Asiat,None,None,None,None,None
810,Mile Time,"Baquerizo Moreno E7-70, Quito, Ecuador",restaurant,🇹🇼,💸,Asiat,Vege/Vegan 🌱,None,None,None,None
811,Barrio Meshica,"15 Rue de la Villette, 75019 Paris, France",restaurant,,💸💸,Hispanique,TheFork 🍴,None,None,None,None

## Address separation

In [12]:
adr_df = privateless_df['address'].str.split(',', expand=True)

In [13]:
adr_df.columns = [f'adr{i+1}' for i in range(adr_df.shape[1])]

## Postal Code Separation

In [14]:
df_pc = adr_df["adr2"].str.split(' ', expand=True)

In [15]:
df_pc.columns = [f'cp{i+1}' for i in range(df_pc.shape[1])]

In [16]:
df_pc = df_pc[["cp2","cp3"]]

In [18]:
print(privateless_df.shape,adr_df.shape,df_pc.shape)

(812, 11) (812, 6) (812, 2)

## Address concatenation

In [17]:
df = pd.concat([privateless_df,adr_df, df_pc], axis=1)

In [22]:
df

,name,address,icon,userComment,tag1,tag2,tag3,tag4,tag5,tag6,tag7,adr1,adr2,adr3,adr4,adr5,adr6,cp2,cp3
0,French Cantine,"65 Avenue Gambetta, 93170 Bagnolet, France",restaurant,Meilleur sandwich que j’ai mangé. Les plats de...,💸,Grec 🥙,Halal,Pâtes 🍝,Validé ✅,None,None,65 Avenue Gambetta,93170 Bagnolet,France,None,None,None,93170,Bagnolet
1,La Maison Du Tacos,"23 Rue Saint-Spire, 91100 Corbeil-Essonnes, Fr...",restaurant,Meilleur endroit pour prendre un tacos FR . 🖕🏾...,💸,Halal,Tacos 🇫🇷,Validé ✅,None,None,None,23 Rue Saint-Spire,91100 Corbeil-Essonnes,France,None,None,None,91100,Corbeil-Essonnes
2,Mamagaya,24 Avenue Henri Barbusse 93700 Drancy France,restaurant,,💸,Grec 🥙,Pâtes 🍝,À faire,None,None,None,24 Avenue Henri Barbusse 93700 Drancy France,None,None,None,None,None,None,None
3,Broadway Coffee,"4 Boulevard Carnot, 93250 Villemomble, France",fastfood,,💸,Burger 🍔🍟,À faire,None,None,None,None,4 Boulevard Carnot,93250 Villemomble,France,None,None,None,93250,Villemomble
4,O'Cheese Naans,"20 Rue Pablo Neruda, 77200 Torcy, France",restaurant,,Burger 🍔🍟,Grec 🥙,💸,À faire,None,None,None,20 Rue Pablo Neruda,77200 Torcy,France,None,None,None,77200,Torcy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
807,Sant Just,"Calle 16A 2-73, 111711 Bogotá, D.C., Colombia",restaurant,,💸💸,Viande,Restaurant,None,None,None,None,Calle 16A 2-73,111711 Bogotá,D.C.,Colombia,None,None,111711,Bogotá
808,Fairuz Café Restaurante / Shawarma Show,"Avenida 6 de Diciembre, N25-23, 170524 Quito, ...",restaurant,,💸,Libanais 🇱🇧,None,None,None,None,None,Avenida 6 de Diciembre,N25-23,170524 Quito,Ecuador,None,None,N25-23,None
809,Chifa Fuzhao (Chifa Fu Zhao),"Avenida 6 de Diciembre, N25-23, 170524 Quito, ...",restaurant,🇨🇳,💸,Asiat,None,None,None,None,None,Avenida 6 de Diciembre,N25-23,170524 Quito,Ecuador,None,None,N25-23,None
810,Mile Time,"Baquerizo Moreno E7-70, Quito, Ecuador",restaurant,🇹🇼,💸,Asiat,Vege/Vegan 🌱,None,None,None,None,Baquerizo Moreno E7-70,Quito,Ecuador,None,None,None,Quito,None
811,Barrio Meshica,"15 Rue de la Villette, 75019 Paris, France",restaurant,,💸💸,Hispanique,TheFork 🍴,None,None,None,None,15 Rue de la Villette,75019 Paris,France,None,None,None,75019,Paris

## Removal of unused columns

In [18]:
df = df.drop(columns=['address','adr2','adr4','adr5','adr6'],axis=1)

## Renaming of columns for better readability

In [19]:
df = df.rename(columns={'adr1':'address', 'adr3':'country', 'cp2':'postalCode', 'cp3':'city'})

## Reordering of the columns

In [20]:
df = df[['name','address', 'city', 'postalCode', 'country', 'icon', 'userComment', 'tag1', 'tag2', 'tag3', 'tag4', 'tag5', 'tag6', 'tag7']]

## Merging dataframe with coordinates values contained in another file

In [21]:
geo_js = json.load(open('mapstr.geojson'))

In [22]:
features = geo_js['features']

In [23]:
df_rows = []

In [24]:
for feature in features:
    properties = feature['properties']
    geometry = feature['geometry']

    name = properties.get('name', '')
    address = properties.get('address', '')
    icon = properties.get('icon', '')

    tags = [tag['name'] for tag in properties.get('tags', [])]

    coordinates = geometry.get('coordinates', [])

    df_row = {
        'name': name,
        'address': address,
        'icon': icon,
        'coordinates': coordinates
    }

    for i, tag in enumerate(tags):
        df_row[f'tag{i + 1}'] = tag

    df_rows.append(df_row)

In [25]:
df_geo = pd.DataFrame(df_rows)

In [26]:
df_geo

,name,address,icon,coordinates,tag1,tag2,tag3,tag4,tag5,tag6,tag7
0,Barrio Meshica,"15 Rue de la Villette, 75019 Paris, France",restaurant,"[2.387355099999999, 48.875464]",💸💸,Hispanique,TheFork 🍴,NaN,NaN,NaN,NaN
1,Mile Time,"Baquerizo Moreno E7-70, Quito, Ecuador",restaurant,"[-78.4890358, -0.2023699]",💸,Asiat,Vege/Vegan 🌱,NaN,NaN,NaN,NaN
2,Chifa Fuzhao (Chifa Fu Zhao),"Avenida 6 de Diciembre, N25-23, 170524 Quito, ...",restaurant,"[-78.4902, -0.20433]",💸,Asiat,NaN,NaN,NaN,NaN,NaN
3,Fairuz Café Restaurante / Shawarma Show,"Avenida 6 de Diciembre, N25-23, 170524 Quito, ...",restaurant,"[-78.49185, -0.205209]",💸,Libanais 🇱🇧,NaN,NaN,NaN,NaN,NaN
4,Sant Just,"Calle 16A 2-73, 111711 Bogotá, D.C., Colombia",restaurant,"[-74.0686226, 4.600679899999999]",💸💸,Viande,Restaurant,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
829,O'Cheese Naans,"20 Rue Pablo Neruda, 77200 Torcy, France",restaurant,"[2.645185499999999, 48.8437061]",Burger 🍔🍟,Grec 🥙,💸,À faire,NaN,NaN,NaN
830,Broadway Coffee,"4 Boulevard Carnot, 93250 Villemomble, France",fastfood,"[2.5116299, 48.88896039999999]",💸,Burger 🍔🍟,À faire,NaN,NaN,NaN,NaN
831,Mamagaya,24 Avenue Henri Barbusse 93700 Drancy France,restaurant,"[2.4435894, 48.9159382]",💸,Grec 🥙,Pâtes 🍝,À faire,NaN,NaN,NaN
832,La Maison Du Tacos,"23 Rue Saint-Spire, 91100 Corbeil-Essonnes, Fr...",restaurant,"[2.483511, 48.612176]",💸,Halal,Tacos 🇫🇷,Validé ✅,NaN,NaN,NaN
833,French Cantine,"65 Avenue Gambetta, 93170 Bagnolet, France",restaurant,"[2.416906, 48.870541]",💸,Grec 🥙,Halal,Pâtes 🍝,Validé ✅,NaN,NaN

## Separation of longitude and latitude coordinates

In [26]:
def format_coordinates(row:str):
    longitude = row[0]
    latitude = row[1]
    return longitude, latitude

In [27]:
df_geo['longitude'], df_geo['latitude'] = zip(*df_geo['coordinates'].apply(format_coordinates))

In [28]:
df_merged = pd.merge(df, df_geo, on='name', how='left')

In [29]:
df_merged = df_merged.drop(columns=['address_y', 'icon_y', 'tag1_y', 'tag2_y', 'tag3_y', 'tag4_y', 'tag5_y', 'tag6_y', 'tag7_y'])

In [30]:
df_merged.columns = [column[:-2] if column.endswith('_x') else column for column in df_merged.columns]

In [32]:
df_merged

,name,address,city,postalCode,country,icon,userComment,tag1,tag2,tag3,tag4,tag5,tag6,tag7,coordinates,longitude,latitude
0,French Cantine,65 Avenue Gambetta,Bagnolet,93170,France,restaurant,Meilleur sandwich que j’ai mangé. Les plats de...,💸,Grec 🥙,Halal,Pâtes 🍝,Validé ✅,None,None,"[2.416906, 48.870541]",2.416906,48.870541
1,La Maison Du Tacos,23 Rue Saint-Spire,Corbeil-Essonnes,91100,France,restaurant,Meilleur endroit pour prendre un tacos FR . 🖕🏾...,💸,Halal,Tacos 🇫🇷,Validé ✅,None,None,None,"[2.483511, 48.612176]",2.483511,48.612176
2,Mamagaya,24 Avenue Henri Barbusse 93700 Drancy France,None,None,None,restaurant,,💸,Grec 🥙,Pâtes 🍝,À faire,None,None,None,"[2.4435894, 48.9159382]",2.443589,48.915938
3,Broadway Coffee,4 Boulevard Carnot,Villemomble,93250,France,fastfood,,💸,Burger 🍔🍟,À faire,None,None,None,None,"[2.5116299, 48.88896039999999]",2.511630,48.888960
4,O'Cheese Naans,20 Rue Pablo Neruda,Torcy,77200,France,restaurant,,Burger 🍔🍟,Grec 🥙,💸,À faire,None,None,None,"[2.645185499999999, 48.8437061]",2.645185,48.843706
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
813,Sant Just,Calle 16A 2-73,Bogotá,111711,D.C.,restaurant,,💸💸,Viande,Restaurant,None,None,None,None,"[-74.0686226, 4.600679899999999]",-74.068623,4.600680
814,Fairuz Café Restaurante / Shawarma Show,Avenida 6 de Diciembre,None,N25-23,170524 Quito,restaurant,,💸,Libanais 🇱🇧,None,None,None,None,None,"[-78.49185, -0.205209]",-78.491850,-0.205209
815,Chifa Fuzhao (Chifa Fu Zhao),Avenida 6 de Diciembre,None,N25-23,170524 Quito,restaurant,🇨🇳,💸,Asiat,None,None,None,None,None,"[-78.4902, -0.20433]",-78.490200,-0.204330
816,Mile Time,Baquerizo Moreno E7-70,None,Quito,Ecuador,restaurant,🇹🇼,💸,Asiat,Vege/Vegan 🌱,None,None,None,None,"[-78.4890358, -0.2023699]",-78.489036,-0.202370
817,Barrio Meshica,15 Rue de la Villette,Paris,75019,France,restaurant,,💸💸,Hispanique,TheFork 🍴,None,None,None,None,"[2.387355099999999, 48.875464]",2.387355,48.875464

## Formatting of address column not well formatted by earlier function

In [31]:
def address_formatting(address:str):
    parts = address.split()
    if len(parts) < 3:
        return
    if address.endswith('France'):
        code_postal = parts[-3]
        pays = parts[-1]
        ville = " ".join(parts[-2:-1])
        return code_postal, ville, pays
    if address.startswith('Centre'):
        code_postal = parts[-1]
        ville = " ".join(parts[-2:-1])
        return code_postal, ville, "France"

In [32]:
df_merged[['Code Postal', 'Ville', 'Pays']] = df_merged['address'].apply(lambda x: pd.Series(address_formatting(x)))
df_merged['city'] = df_merged['city'].fillna(df_merged['Ville'])
df_merged['postalCode'] = df_merged['postalCode'].fillna(df_merged['Code Postal'])
df_merged['country'] = df_merged['country'].fillna(df_merged['Pays'])
df_merged = df_merged.drop(columns=['Code Postal', 'Ville', 'Pays'])

In [33]:
df = df_merged

In [34]:
df = df.fillna("")

In [38]:
df[df['city'].str.contains('London')]

,name,address,city,postalCode,country,icon,userComment,tag1,tag2,tag3,tag4,tag5,tag6,tag7,coordinates,longitude,latitude
397,Peggy Porschen - Belgravia,116 Ebury Street,London,Belgravia,,shopping,,Salon de thé 🍵,À faire,,,,,,"[-0.1505416, 51.4933026]",-0.150542,51.493303

In [35]:
df.loc[171, ['city', 'postalCode', 'country']] = ['London', 'SE1 9AL', 'United Kingdom']
df.loc[216, ['city', 'postalCode', 'country']] = ['London', 'NW1 8AF', 'United Kingdom']
df.loc[317, ['city', 'postalCode', 'country']] = ['London', 'WC1A 1ES', 'United Kingdom']
df.loc[398, ['city', 'postalCode', 'country']] = ['London', 'SW9 8PQ', 'United Kingdom']
df.loc[397, ['postalCode', 'country']] = ['SW1W 9QQ', 'United Kingdom']

In [40]:
df[df['city'].str.contains('Madrid') | df['postalCode'].str.contains('Madrid') | df['country'].str.contains('Madrid')]

,name,address,city,postalCode,country,icon,userComment,tag1,tag2,tag3,tag4,tag5,tag6,tag7,coordinates,longitude,latitude
202,HABANERA,Calle de Génova,,28,28004 Madrid,restaurant,,Restaurant,À faire,,,,,,"[-3.6917744, 40.4253604]",-3.691774,40.425360
203,Chocolatería San Gines,Pasadizo San Ginés,,5,28013 Madrid,generic,,Chocolaterie 🍫,À faire,,,,,,"[-3.7067806, 40.4167805]",-3.706781,40.416781
204,San Miguel Market,Plaza de San Miguel,,3,28005 Madrid,restaurant,,Restaurant,À faire,,,,,,"[-3.7087575, 40.41511060000001]",-3.708757,40.415111
205,Restaurante Ten Con Ten,Cl. de Ayala,,6,28001 Madrid,restaurant,,Restaurant,À faire,,,,,,"[-3.6887501, 40.42777580000001]",-3.688750,40.427776
207,Frida,Calle de San Gregorio 8,Madrid,Madrid,,restaurant,,Restaurant,💸💸,À faire,,,,,"[-3.697049499999999, 40.4239833]",-3.697049,40.423983

In [36]:
df.loc[202, ['city', 'postalCode', 'country']] = ['Madrid', '28004', 'Spain']
df.loc[203, ['city', 'postalCode', 'country']] = ['Madrid', '28013', 'Spain']
df.loc[204, ['city', 'postalCode', 'country']] = ['Madrid', '28005', 'Spain']
df.loc[205, ['city', 'postalCode', 'country']] = ['Madrid', '28001', 'Spain']
df.loc[207, ['city', 'postalCode', 'country']] = ['Madrid', '28004', 'Spain']

In [55]:
df[df['country'].str.contains('Barcelona')]

,name,address,city,postalCode,country,icon,userComment,tag1,tag2,tag3,tag4,tag5,tag6,tag7,coordinates
208,El Kiosko,Av. de Josep Tarradellas,Barcelona,08029,Spain,restaurant,,Restaurant,🍴 inconnu,À faire,,,,,"[2.143665, 41.39153400000001]"
209,Kiosko de Bacoa,Av. del Marquès de l'Argentera,Barcelona,08003,Spain,restaurant,,Restaurant,À faire,,,,,,"[2.1836997, 41.38350870000001]"
210,Santa Burg,Carrer del Vallespir,Barcelona,08014,Spain,restaurant,,Restaurant,À faire,,,,,,"[2.136761299999999, 41.37972909999999]"
211,BRO Room,Carrer de Còrsega,Barcelona,08025,Spain,restaurant,,Restaurant,💸,À faire,,,,,"[2.1736622, 41.4071164]"
212,Timesburg Paris,Carrer de París,Barcelona,08029,Spain,restaurant,,Restaurant,À faire,TheFork 🍴,,,,,"[2.1468417, 41.38909020000001]"
213,DE PAULA - L´HAMBURGUESERIA DEL POBLE SEC,Carrer de la Creu dels Molers,Barcelona,08004,Spain,restaurant,,💸,Burger 🍔🍟,À faire,,,,,"[2.16135, 41.372399]"
215,Makamaka,Passeig de Joan de Borbó Comte de Barcelona,Barcelona,08039,Spain,restaurant,,Restaurant,À faire,,,,,,"[2.188563900000001, 41.3757436]"

In [37]:
df.loc[208, ['city', 'postalCode', 'country']] = ['Barcelona', '08029', 'Spain']
df.loc[209, ['city', 'postalCode', 'country']] = ['Barcelona', '08003', 'Spain']
df.loc[210, ['city', 'postalCode', 'country']] = ['Barcelona', '08014', 'Spain']
df.loc[211, ['city', 'postalCode', 'country']] = ['Barcelona', '08025', 'Spain']
df.loc[212, ['city', 'postalCode', 'country']] = ['Barcelona', '08029', 'Spain']
df.loc[213, ['city', 'postalCode', 'country']] = ['Barcelona', '08004', 'Spain']
df.loc[215, ['city', 'postalCode', 'country']] = ['Barcelona', '08039', 'Spain']

In [57]:
df[df['city'].str.contains('NY') | df['postalCode'].str.contains('NY') | df['country'].str.contains('NY')]

,name,address,city,postalCode,country,icon,userComment,tag1,tag2,tag3,tag4,tag5,tag6,tag7,coordinates
176,Dos Toros Taqueria,11 Carmine St,York,New,NY 10014,restaurant,,Restaurant,Hispanique,À faire,,,,,"[-74.00226669999999, 40.7305402]"
186,Wendy's,335 5th Ave,York,New,NY 10016,restaurant,,Burger 🍔🍟,À faire,,,,,,"[-73.98483399999999, 40.7477751]"
187,Chip NYC,W 14th St,York,New,NY 10014,cafe,,Cookie 🍪,À faire,,,,,,"[-74.004787, 40.74087249999999]"
195,Best Halal,W 53rd St New York,10019,NY,,restaurant,,Halal,Maghreb/Moyen-Orient,À faire,,,,,"[-73.9793609, 40.76183350000001]"
196,El rey Del Taco Truck,3301 30th Ave,,Astoria,NY 11103,restaurant,,Hispanique,À faire,,,,,,"[-73.9193243, 40.7662194]"
197,Young xinjiang bbq cart,2 Forsyth St,York,New,NY 10002,restaurant,,Restaurant,À faire,,,,,,"[-73.99387109999999, 40.7136538]"
198,Van Leeuwen Artisan Ice Cream,48 E 7th St,York,New,NY 10003,icecream,,Glaces 🍨🍦,À faire,,,,,,"[-73.9876914, 40.7276926]"
199,Desi Food Truck,1221 Ave of the Americas,York,New,NY 10020,restaurant,Indien,Halal,Asiat,À faire,,,,,"[-73.9803913, 40.7602489]"
200,Hard Times Sundaes,5700 Avenue U,,Brooklyn,NY 11234,restaurant,,Burger 🍔🍟,💸,À faire,,,,,"[-73.9164586, 40.611972]"
201,Red Hook Lobster Pound,284 Van Brunt St,,Brooklyn,NY 11231,restaurant,,Restaurant,À faire,,,,,,"[-74.0103105, 40.6797578]"
311,Murray's Bagels,500 Avenue of the Americas,York,New,NY 10011,restaurant,,Sandwich 🥪,💸💸,À faire,,,,,"[-73.9972943, 40.7363873]"
314,Magnolia Bakery,1240 6th Ave New York,10020,NY,,supermarket,,Pâtisseries,💸💸,À faire,,,,,"[-73.98055760000001, 40.75926889999999]"
368,Little Cupcake Bakeshop,30 Prince St,York,New,NY 10012,restaurant,,Florian On Air,Pâtisseries,À faire,,,,,"[-73.994852, 40.722932]"
369,Flip'n Toss,82 Christopher St,York,New,NY 10014,restaurant,,Florian On Air,💸💸,Burger 🍔🍟,À faire,,,,"[-74.0036184, 40.73340510000001]"
370,"Burger, Inc.",353 W 14th St,York,New,NY 10014,restaurant,,Florian On Air,Burger 🍔🍟,À faire,,,,,"[-74.00469580000001, 40.7408498]"
371,Red Lobster,5 Times Square,York,New,NY 10036,restaurant,,Florian On Air,Poisson 🐟,À faire,,,,,"[-73.98752999999999, 40.755587]"
372,Chick'nCone,353 W 14th St,York,New,NY 10014,restaurant,,Florian On Air,Poulet 🐔,À faire,,,,,"[-73.982463, 40.76756109999999]"
373,Jacob Soul Food,373 Malcolm X Blvd New York,10027,NY,,restaurant,,Florian On Air,Soul Food,À faire,,,,,"[-73.94394980000001, 40.8102838]"
407,Applebee's,205 W 50th St,York,New,NY 10019,restaurant,,Restaurant,À faire,,,,,,"[-73.98357779999999, 40.7613731]"
436,Arby's,611 8th Ave,York,New,NY 10018,restaurant,,Restaurant,💸💸,À faire,,,,,"[-73.99124090000001, 40.7558174]"

In [38]:
df.loc[176, ['city', 'postalCode', 'country']] = ['New-York', '10014', 'USA']
df.loc[186, ['city', 'postalCode', 'country']] = ['New-York', '10016', 'USA']
df.loc[187, ['city', 'postalCode', 'country']] = ['New-York', '10014', 'USA']
df.loc[195, ['city', 'postalCode', 'country']] = ['New-York', '10019', 'USA']
df.loc[196, ['city', 'postalCode', 'country']] = ['New-York', '11103', 'USA']
df.loc[197, ['city', 'postalCode', 'country']] = ['New-York', '10002', 'USA']
df.loc[198, ['city', 'postalCode', 'country']] = ['New-York', '10003', 'USA']
df.loc[199, ['city', 'postalCode', 'country']] = ['New-York', '10020', 'USA']
df.loc[200, ['city', 'postalCode', 'country']] = ['New-York', '11234', 'USA']
df.loc[201, ['city', 'postalCode', 'country']] = ['New-York', '11231', 'USA']

In [59]:
df

,name,address,city,postalCode,country,icon,userComment,tag1,tag2,tag3,tag4,tag5,tag6,tag7,coordinates
0,French Cantine,65 Avenue Gambetta,Bagnolet,93170,France,restaurant,Meilleur sandwich que j’ai mangé. Les plats de...,💸,Grec 🥙,Halal,Pâtes 🍝,Validé ✅,,,"[2.416906, 48.870541]"
1,La Maison Du Tacos,23 Rue Saint-Spire,Corbeil-Essonnes,91100,France,restaurant,Meilleur endroit pour prendre un tacos FR . 🖕🏾...,💸,Halal,Tacos 🇫🇷,Validé ✅,,,,"[2.483511, 48.612176]"
2,Mamagaya,24 Avenue Henri Barbusse 93700 Drancy France,Drancy,93700,France,restaurant,,💸,Grec 🥙,Pâtes 🍝,À faire,,,,"[2.4435894, 48.9159382]"
3,Broadway Coffee,4 Boulevard Carnot,Villemomble,93250,France,fastfood,,💸,Burger 🍔🍟,À faire,,,,,"[2.5116299, 48.88896039999999]"
4,O'Cheese Naans,20 Rue Pablo Neruda,Torcy,77200,France,restaurant,,Burger 🍔🍟,Grec 🥙,💸,À faire,,,,"[2.645185499999999, 48.8437061]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
813,Sant Just,Calle 16A 2-73,Bogotá,111711,D.C.,restaurant,,💸💸,Viande,Restaurant,,,,,"[-74.0686226, 4.600679899999999]"
814,Fairuz Café Restaurante / Shawarma Show,Avenida 6 de Diciembre,,N25-23,170524 Quito,restaurant,,💸,Libanais 🇱🇧,,,,,,"[-78.49185, -0.205209]"
815,Chifa Fuzhao (Chifa Fu Zhao),Avenida 6 de Diciembre,,N25-23,170524 Quito,restaurant,🇨🇳,💸,Asiat,,,,,,"[-78.4902, -0.20433]"
816,Mile Time,Baquerizo Moreno E7-70,,Quito,Ecuador,restaurant,🇹🇼,💸,Asiat,Vege/Vegan 🌱,,,,,"[-78.4890358, -0.2023699]"
817,Barrio Meshica,15 Rue de la Villette,Paris,75019,France,restaurant,,💸💸,Hispanique,TheFork 🍴,,,,,"[2.387355099999999, 48.875464]"

In [39]:
df.loc[15, ['city', 'postalCode', 'country']] = ['Paris', '75005', 'France']
df.loc[16, ['city', 'postalCode', 'country']] = ['Le Kremlin-Bicêtre', '94270', 'France']
df.loc[33, ['city']] = ['Le Kremlin-Bicêtre']
df.loc[46, ['city', 'postalCode', 'country']] = ['Paris', '75002', 'France']
df.loc[51, ['city', 'postalCode', 'country']] = ['Paris', '75011', 'France']
df.loc[65, ['city', 'postalCode', 'country']] = ['Paris', '75018', 'France']
df.loc[75, ['city', 'postalCode', 'country']] = ['Chelles', '77500', 'France']
df.loc[80, ['city', 'postalCode', 'country']] = ['Paris', '75002', 'France']
df.loc[82, ['city', 'postalCode', 'country']] = ['Paris', '75001', 'France']
df.loc[84:87, ['postalCode']] = ['75016']
df.loc[90, ['city', 'postalCode', 'country']] = ['Paris', '75007', 'France']
df.loc[91, ['city', 'postalCode', 'country']] = ['Montreuil', '93100', 'France']
df.loc[95, ['city', 'postalCode', 'country']] = ['Paris', '75015', 'France']
df.loc[99, ['city', 'postalCode', 'country']] = ['Paris', '75019', 'France']
df.loc[100, ['city', 'postalCode', 'country']] = ['Paris', '75019', 'France']
df.loc[104, ['city', 'postalCode', 'country']] = ['Paris', '75002', 'France']
df.loc[107, ['city', 'postalCode', 'country']] = ['Paris', '75001', 'France']
df.loc[115, ['city']] = ['Les Lilas']
df.loc[126, ['city', 'postalCode']] = ['La Courneuve', '93120']
df.loc[147, ['city', 'postalCode', 'country']] = ['Cenon', '33150', 'France']
df.loc[158, ['city', 'postalCode', 'country']] = ['Paris', '75013', 'France']
df.loc[161, ['city', 'postalCode', 'country']] = ['Paris', '75002', 'France']
df.loc[162, ['city', 'postalCode', 'country']] = ['Paris', '75002', 'France']
df.loc[163, ['city', 'postalCode', 'country']] = ['Paris', '75011', 'France']
df.loc[164, ['city', 'postalCode', 'country']] = ['Paris', '75004', 'France']
df.loc[172, ['postalCode']] = ['75018']
df.loc[175, ['city', 'postalCode', 'country']] = ['Los Angeles', '90006', 'USA']
df.loc[178, ['city', 'postalCode', 'country']] = ['Paris', '75009', 'France']
df.loc[185, ['city', 'postalCode', 'country']] = ['London', 'E20', 'United Kingdom']
df.loc[192, ['city', 'postalCode', 'country']] = ['Paris', '75013', 'France']
df.loc[214, ['city', 'postalCode', 'country']] = ['Santa Caterina', '08003', 'Spain']
df.loc[217, ['city', 'postalCode', 'country']] = ['Noisy-le-Grand', '93160', 'France']
df.loc[219, ['city', 'postalCode', 'country']] = ['Paris', '75011', 'France']
df.loc[319, ['city', 'postalCode', 'country']] = ['Las Vegas', '89101', 'USA']
df.loc[321, ['city', 'postalCode', 'country']] = ['San Francisco', '94102', 'USA']
df.loc[361, ['city', 'postalCode', 'country']] = ['Montréal', 'H2X', 'Canada']
df.loc[362, ['city', 'postalCode', 'country']] = ['San Francisco', '94102', 'USA']
df.loc[363, ['city', 'postalCode', 'country']] = ['Playa del Carmen', '77720', 'Mexico']
df.loc[364, ['city', 'postalCode', 'country']] = ['Key West', '33040', 'USA']
df.loc[365, ['city', 'postalCode', 'country']] = ['Miami', '33133', 'USA']
df.loc[366:367, ['city', 'postalCode', 'country']] = ['Miami', '33139', 'USA']
df.loc[368, ['city', 'postalCode', 'country']] = ['New-York', '10012', 'USA']
df.loc[369, ['city', 'postalCode', 'country']] = ['New-York', '10014', 'USA']
df.loc[370, ['city', 'postalCode', 'country']] = ['New-York', '10014', 'USA']
df.loc[371, ['city', 'postalCode', 'country']] = ['New-York', '10036', 'USA']
df.loc[372, ['city', 'postalCode', 'country']] = ['New-York', '10014', 'USA']
df.loc[373, ['city', 'postalCode', 'country']] = ['New-York', '10027', 'USA']
df.loc[396, ['city', 'postalCode', 'country']] = ['London', 'W1J 0LF', 'United Kingdom']
df.loc[399, ['city', 'postalCode', 'country']] = ['London', 'SW9 8PQ', 'United Kingdom']
df.loc[407, ['city', 'postalCode', 'country']] = ['New-York', '10019', 'USA']
df.loc[409, ['city', 'postalCode']] = ['Amsterdam', '1017']
df.loc[414, ['city', 'postalCode', 'country']] = ['Seattle', '98122', 'USA']
df.loc[506, ['city', 'postalCode', 'country']] = ['Napoli', '80127', 'Italy']
df.loc[623, ['city', 'postalCode', 'country']] = ['Ixelles', '1050', 'Belgique']
df.loc[624, ['city', 'postalCode', 'country']] = ['Bruxelles', '1000', 'Belgique']
df.loc[625, ['city', 'postalCode', 'country']] = ['Ixelles', '1050', 'Belgique']
df.loc[630, ['city', 'postalCode', 'country']] = ['Bruxelles', '1000', 'Belgique']
df.loc[641, ['country']] = ['Belgique']
df.loc[643, ['city', 'postalCode', 'country']] = ['Ixelles', '1050', 'Belgique']
df.loc[644, ['country']] = ['Belgique']
df.loc[645, ['country']] = ['Belgique']
df.loc[646, ['city', 'postalCode', 'country']] = ['Bruxelles', '1000', 'Belgique']
df.loc[647, ['city', 'postalCode', 'country']] = ['Bruxelles', '1000', 'Belgique']
df.loc[648, ['city', 'postalCode', 'country']] = ['Bruxelles', '1000', 'Belgique']
df.loc[656, ['country']] = ['Allemagne']
df.loc[660, ['country']] = ['Allemagne']
df.loc[664, ['country']] = ['Allemagne']
df.loc[665, ['city', 'postalCode', 'country']] = ['Berlin', '10178', 'Allemagne']
df.loc[666, ['city', 'postalCode', 'country']] = ['Berlin', '10999', 'Allemagne']
df.loc[667, ['city', 'postalCode', 'country']] = ['Berlin', '10117', 'Allemagne']
df.loc[668, ['city', 'postalCode', 'country']] = ['Berlin', '10789', 'Allemagne']
df.loc[682:683, ['city', 'postalCode', 'country']] = ['Genève', '1201', 'Suisse']
df.loc[697:699, ['country']] = ['France']
df.loc[700, ['city', 'postalCode', 'country']] = ['Luxembourg', '2227', 'Luxembourg']
df.loc[701, ['city', 'postalCode', 'country']] = ['Luxembourg', '1247', 'Luxembourg']
df.loc[801, ['city', 'postalCode', 'country']] = ['Playa del Carmen', '77710', 'Mexico']
df.loc[802, ['city', 'postalCode', 'country']] = ['Antigua Guatemala', '', 'Guatemala']
df.loc[803:806, ['city', 'postalCode', 'country']] = ['Panajachel', '', 'Guatemala']
df.loc[807, ['city', 'postalCode', 'country']] = ['Ciudad de Guatemala', '', 'Guatemala']
df.loc[809:813, ['city', 'postalCode', 'country']] = ['Bogotá', '', 'Colombia']
df.loc[814:816, ['city', 'postalCode', 'country']] = ['Quito', '170524', 'Ecuador']

In [54]:
df

,name,address,city,postalCode,country,icon,userComment,tag1,tag2,tag3,tag4,tag5,tag6,tag7,coordinates,longitude,latitude
0,French Cantine,65 Avenue Gambetta,Bagnolet,93170,France,restaurant,Meilleur sandwich que j’ai mangé. Les plats de...,💸,Grec 🥙,Halal,Pâtes 🍝,Validé ✅,None,None,"[2.416906, 48.870541]",2.416906,48.870541
1,La Maison Du Tacos,23 Rue Saint-Spire,Corbeil-Essonnes,91100,France,restaurant,Meilleur endroit pour prendre un tacos FR . 🖕🏾...,💸,Halal,Tacos 🇫🇷,Validé ✅,None,None,None,"[2.483511, 48.612176]",2.483511,48.612176
2,Mamagaya,24 Avenue Henri Barbusse 93700 Drancy France,Drancy,93700,France,restaurant,,💸,Grec 🥙,Pâtes 🍝,À faire,None,None,None,"[2.4435894, 48.9159382]",2.443589,48.915938
3,Broadway Coffee,4 Boulevard Carnot,Villemomble,93250,France,fastfood,,💸,Burger 🍔🍟,À faire,None,None,None,None,"[2.5116299, 48.88896039999999]",2.511630,48.888960
4,O'Cheese Naans,20 Rue Pablo Neruda,Torcy,77200,France,restaurant,,Burger 🍔🍟,Grec 🥙,💸,À faire,None,None,None,"[2.645185499999999, 48.8437061]",2.645185,48.843706
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
813,Sant Just,Calle 16A 2-73,Bogotá,,Colombia,restaurant,,💸💸,Viande,Restaurant,None,None,None,None,"[-74.0686226, 4.600679899999999]",-74.068623,4.600680
814,Fairuz Café Restaurante / Shawarma Show,Avenida 6 de Diciembre,Quito,170524,Ecuador,restaurant,,💸,Libanais 🇱🇧,None,None,None,None,None,"[-78.49185, -0.205209]",-78.491850,-0.205209
815,Chifa Fuzhao (Chifa Fu Zhao),Avenida 6 de Diciembre,Quito,170524,Ecuador,restaurant,🇨🇳,💸,Asiat,None,None,None,None,None,"[-78.4902, -0.20433]",-78.490200,-0.204330
816,Mile Time,Baquerizo Moreno E7-70,Quito,170524,Ecuador,restaurant,🇹🇼,💸,Asiat,Vege/Vegan 🌱,None,None,None,None,"[-78.4890358, -0.2023699]",-78.489036,-0.202370
817,Barrio Meshica,15 Rue de la Villette,Paris,75019,France,restaurant,,💸💸,Hispanique,TheFork 🍴,None,None,None,None,"[2.387355099999999, 48.875464]",2.387355,48.875464

In [63]:
df.isnull().sum()

name             0
address          0
city             0
postalCode       0
country          0
icon             2
userComment      0
tag1             0
tag2             7
tag3           197
tag4           547
tag5           742
tag6           797
tag7           813
coordinates      0
longitude        0
latitude         0
dtype: int64

In [41]:
df[~df['city'].notna()]

,name,address,city,postalCode,country,icon,userComment,tag1,tag2,tag3,tag4,tag5,tag6,tag7,coordinates,longitude,latitude
206,Restaurante Casa Lucio,Calle Cava Baja,NaN,35,BAJO,restaurant,,Restaurant,💸💸,À faire,None,None,None,None,"[-3.709716, 40.412064]",-3.709716,40.412064
233,El Guacamole,35 Rue Yves Toudic,NaN,Paris,NaN,restaurant,,💸,Hispanique,À faire,None,None,None,None,"[2.362184, 48.87136479999999]",2.362184,48.871365
282,Jimmy 2 fois,15 Rue Letort Paris 75018,NaN,NaN,NaN,restaurant,,Pizza 🍕,💸💸,Validé ✅,TheFork 🍴,None,None,None,"[2.3429737, 48.8943618]",2.342974,48.894362
315,Maison Dandoy - Galeries,BeenhouwersStraat Brussels Belgium,NaN,NaN,NaN,supermarket,,Pâtisseries,💸💸,À faire,None,None,None,None,"[4.351577999999999, 50.847419]",4.351578,50.847419
332,Roberta,5 bis rue la Vieuville Abbesses Paris 75018,NaN,NaN,NaN,restaurant,,Florian On Air,💸💸,Pizza 🍕,À faire,TheFork 🍴,None,None,"[2.339037, 48.8846968]",2.339037,48.884697
377,Le Grenier à Pain Abbesses Bodian,38 rue Des Abesses Paris 75018,NaN,NaN,NaN,restaurant,,Boulangerie 🥖,💸,À faire,None,None,None,None,"[2.3367337, 48.88531829999999]",2.336734,48.885318
381,L'Antica Pizzeria da Michele,Via Cesare Sersale,NaN,1,80139 Napoli NA,restaurant,,Pizza 🍕,À faire,None,None,None,None,None,"[14.2633002, 40.8497563]",14.263300,40.849756
411,faggio,,NaN,NaN,72 Rue de Rochechouart,restaurant,,Pizza 🍕,🍴 inconnu,À faire,None,None,None,None,"[2.346708, 48.8816416]",2.346708,48.881642
418,Baba Zulu,23 Rue Beaurepaire Paris 75010,NaN,NaN,NaN,restaurant,,Soul Food,💸💸,None,None,None,None,None,"[2.3639914, 48.8711079]",2.363991,48.871108
421,Pizza Di Loretta - Rodier,62 Rue Rodier Paris 75009,NaN,NaN,NaN,restaurant,,Pizza 🍕,💸💸,À faire,None,None,None,None,"[2.3440565, 48.88061159999999]",2.344057,48.880612
461,Gino Sorbillo Antica Pizzeria,Via dei Tribunali,NaN,32,80134 Napoli,restaurant,,Pizza 🍕,À faire,None,None,None,None,None,"[14.2553176, 40.85041289999999]",14.255318,40.850413
469,Yummy & Guiltfree,3 rue du Temple 75004 Paris,NaN,NaN,NaN,fastfood,,Pâtisseries,À faire,None,None,None,None,None,"[2.35251, 48.85755]",2.352510,48.857550
512,Alfred Burger - Noisy,2 Avenue Aristide Briand,NaN,93160,Noisy-le-Grand,restaurant,,Burger 🍔🍟,💸💸,À faire,None,None,None,None,"[2.5525041, 48.84855210000001]",2.552504,48.848552
534,CHEESERS - RESTAURANT REPUBLIQUE ET FOOD TRUCK,3 rue Yves Toudic Paris 75010,NaN,NaN,NaN,restaurant,,Sandwich 🥪,À faire,TheFork 🍴,None,None,None,None,"[2.3641372, 48.8693403]",2.364137,48.869340
541,Jacques Genin Turenne,133 rue de Turenne 75003 Paris,NaN,NaN,NaN,restaurant,"Coumarine, Praliesse, L, Tonka Teck 😋🤤",💸💸,Chocolaterie 🍫,Validé ✅,None,None,None,None,"[2.3645631, 48.8644515]",2.364563,48.864452
547,Rodizio Brazil - Colombes,157 Bd Charles De Gaulle Colombes 92700,NaN,NaN,NaN,restaurant,,Viande,À faire,None,None,None,None,None,"[2.2267301, 48.91582950000001]",2.226730,48.915830
550,Constantia,94 Rue des Martyrs,NaN,NaN,NaN,restaurant,,Pizza 🍕,💸💸,À faire,2️⃣,None,None,None,"[2.33982, 48.88399]",2.339820,48.883990
554,ALDI,12 rue De L'Université Noisy Le Grand 93160,NaN,NaN,NaN,supermarket,,À bats la hess,💸,Validé ✅,None,None,None,None,"[2.560453, 48.83683]",2.560453,48.836830
555,CRISPY SOUL Paris 15,101 Rue Brancion Paris 75015,NaN,NaN,NaN,restaurant,"L’accueil, le service et le repas étaient au t...",Soul Food,💸💸,Validé ✅,Halal,None,None,None,"[2.30212, 48.83052]",2.302120,48.830520
562,La Maison du Zéro Déchet,1 passage Emma Calvé Paris 75012,NaN,NaN,NaN,family,,Bio/Vegan,À faire,None,None,None,None,None,"[2.385891914367676, 48.84823989868164]",2.385892,48.848240
586,Princesse Café,32 Rue Bichat Paris 75010,NaN,NaN,NaN,restaurant,,💸💸,Brunch,Validé ✅,TheFork 🍴,None,None,None,"[2.3683456, 48.871201]",2.368346,48.871201
611,Julhès Paris,54 Rue du Faubourg Saint-Denis 75010 Paris,NaN,NaN,NaN,shopping,,💸💸,Boulangerie 🥖,Epicierie Fine,Validé ✅,None,None,None,"[2.354268900000001, 48.87232909999999]",2.354269,48.872329
614,MaMi,44 Rue du Faubourg du Temple Paris 75011,NaN,NaN,NaN,restaurant,,💸,Sandwich 🥪,Validé ✅,None,None,None,None,"[2.3691971, 48.8692692]",2.369197,48.869269
704,Blend Hamburger Charonne,15 Rue de Charonne Paris 75011,NaN,NaN,NaN,restaurant,,💸💸,Burger 🍔🍟,Validé ✅,None,None,None,None,"[2.3744885, 48.85297060000001]",2.374489,48.852971
735,Pepite cookie - Gambetta,Bordeaux 33000,NaN,NaN,NaN,restaurant,,💸💸,Cookie 🍪,None,None,None,None,None,"[-0.5794452428817749, 44.84059524536133]",-0.579445,44.840595

In [40]:
df.loc[206, ['city', 'postalCode', 'country']] = ['Madrid', '28005', 'Spain']
df.loc[233, ['city', 'postalCode', 'country']] = ['Paris', '75010', 'France']
df.loc[282, ['city', 'postalCode', 'country']] = ['Paris', '75018', 'France']
df.loc[315, ['city', 'postalCode', 'country']] = ['Bruxelles', '1000', 'Belgique']
df.loc[377, ['city', 'postalCode', 'country']] = ['Paris', '75018', 'France']
df.loc[381, ['city', 'postalCode', 'country']] = ['Napoli', '80139', 'Italy']
df.loc[411, ['city', 'postalCode', 'country']] = ['Paris', '75009', 'France']
df.loc[418, ['city', 'postalCode', 'country']] = ['Paris', '75010', 'France']
df.loc[421, ['city', 'postalCode', 'country']] = ['Paris', '75009', 'France']

df.loc[461, ['city', 'postalCode', 'country']] = ['Napoli', '80134', 'Italy']
df.loc[469, ['city', 'postalCode', 'country']] = ['Paris', '75004', 'France']
df.loc[512, ['city', 'postalCode', 'country']] = ['Noisy-le-Grand', '93160', 'France']
df.loc[534, ['city', 'postalCode', 'country']] = ['Paris', '75010', 'France']
df.loc[541, ['city', 'postalCode', 'country']] = ['Paris', '75003', 'France']
df.loc[547, ['city', 'postalCode', 'country']] = ['Colombes', '92700', 'France']
df.loc[550, ['city', 'postalCode', 'country']] = ['Paris', '75018', 'France']
df.loc[554, ['city', 'postalCode', 'country']] = ['Noisy-le-Grand', '93160', 'France']
df.loc[555, ['city', 'postalCode', 'country']] = ['Paris', '75015', 'France']
df.loc[562, ['city', 'postalCode', 'country']] = ['Paris', '75012', 'France']
df.loc[586, ['city', 'postalCode', 'country']] = ['Paris', '75010', 'France']
df.loc[611, ['city', 'postalCode', 'country']] = ['Paris', '75010', 'France']
df.loc[614, ['city', 'postalCode', 'country']] = ['Paris', '75011', 'France']
df.loc[704, ['city', 'postalCode', 'country']] = ['Paris', '75011', 'France']
df.loc[735, ['city', 'postalCode', 'country']] = ['Bordeaux', '33000', 'France']

In [46]:
df

,name,address,city,postalCode,country,icon,userComment,tag1,tag2,tag3,tag4,tag5,tag6,tag7,coordinates,longitude,latitude
0,French Cantine,65 Avenue Gambetta,Bagnolet,93170,France,restaurant,Meilleur sandwich que j’ai mangé. Les plats de...,💸,Grec 🥙,Halal,Pâtes 🍝,Validé ✅,None,None,"[2.416906, 48.870541]",2.416906,48.870541
1,La Maison Du Tacos,23 Rue Saint-Spire,Corbeil-Essonnes,91100,France,restaurant,Meilleur endroit pour prendre un tacos FR . 🖕🏾...,💸,Halal,Tacos 🇫🇷,Validé ✅,None,None,None,"[2.483511, 48.612176]",2.483511,48.612176
2,Mamagaya,24 Avenue Henri Barbusse 93700 Drancy France,Drancy,93700,France,restaurant,,💸,Grec 🥙,Pâtes 🍝,À faire,None,None,None,"[2.4435894, 48.9159382]",2.443589,48.915938
3,Broadway Coffee,4 Boulevard Carnot,Villemomble,93250,France,fastfood,,💸,Burger 🍔🍟,À faire,None,None,None,None,"[2.5116299, 48.88896039999999]",2.511630,48.888960
4,O'Cheese Naans,20 Rue Pablo Neruda,Torcy,77200,France,restaurant,,Burger 🍔🍟,Grec 🥙,💸,À faire,None,None,None,"[2.645185499999999, 48.8437061]",2.645185,48.843706
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
813,Sant Just,Calle 16A 2-73,Bogotá,,Colombia,restaurant,,💸💸,Viande,Restaurant,None,None,None,None,"[-74.0686226, 4.600679899999999]",-74.068623,4.600680
814,Fairuz Café Restaurante / Shawarma Show,Avenida 6 de Diciembre,Quito,170524,Ecuador,restaurant,,💸,Libanais 🇱🇧,None,None,None,None,None,"[-78.49185, -0.205209]",-78.491850,-0.205209
815,Chifa Fuzhao (Chifa Fu Zhao),Avenida 6 de Diciembre,Quito,170524,Ecuador,restaurant,🇨🇳,💸,Asiat,None,None,None,None,None,"[-78.4902, -0.20433]",-78.490200,-0.204330
816,Mile Time,Baquerizo Moreno E7-70,Quito,170524,Ecuador,restaurant,🇹🇼,💸,Asiat,Vege/Vegan 🌱,None,None,None,None,"[-78.4890358, -0.2023699]",-78.489036,-0.202370
817,Barrio Meshica,15 Rue de la Villette,Paris,75019,France,restaurant,,💸💸,Hispanique,TheFork 🍴,None,None,None,None,"[2.387355099999999, 48.875464]",2.387355,48.875464

In [42]:
df.loc[25, ['country']] = ['France']
df.loc[30, ['city','postalCode','country']] = ['Paris','75011','France']
df.loc[71, ['postalCode']] = ['75006']
df.loc[235, ['city','postalCode','country']] = ['Paris','75001','France']
df.loc[238, ['city','postalCode','country']] = ['Paris','75009','France']
df.loc[239, ['city','postalCode','country']] = ['Paris','75003','France']
df.loc[258, ['city','postalCode']] = ['Le Blanc-Mesnil','France']
df.loc[265, ['city','postalCode', 'country']] = ['Paris','75010','France']
df.loc[269, ['city']] = ['Paris']
df.loc[270, ['city','postalCode', 'country']] = ['Paris','75020','France']
df.loc[285, ['postalCode']] = ['75011']
df.loc[296, ['city','postalCode', 'country']] = ['Paris','75011','France']

df.loc[301, ['city','postalCode', 'country']] = ['Paris','75009','France']
df.loc[302, ['city','postalCode', 'country']] = ['Paris','75004','France']
df.loc[304, ['city','postalCode', 'country']] = ['Paris','75004','France']
df.loc[307, ['postalCode']] = ['75005']
df.loc[311, ['city','postalCode', 'country']] = ['New-York','10011','USA']
df.loc[314, ['city','postalCode', 'country']] = ['New-York','10020','USA']
df.loc[318, ['city','postalCode', 'country']] = ['Newcastle upon Tyne','NE1 5JE','United Kingdom']
df.loc[320, ['city','postalCode', 'country']] = ['San Francisco','94108','USA']
df.loc[332, ['city','postalCode', 'country']] = ['Paris','75018','France']
df.loc[334, ['city','postalCode', 'country']] = ['Le Raincy','93340','France']
df.loc[337, ['postalCode']] = ['59000']
df.loc[338, ['city','postalCode', 'country']] = ['Lille','59000','France']
df.loc[343, ['postalCode']] = ['76000']
df.loc[359, ['city','postalCode', 'country']] = ['Lyon','69005','France']
df.loc[360, ['city','postalCode', 'country']] = ['Sevilla','41004','Spain']
df.loc[380, ['city','postalCode', 'country']] = ['Los Angeles','91403','USA']
df.loc[385, ['city','postalCode', 'country']] = ['London','SE1','United Kingdom']
df.loc[415, ['city','postalCode', 'country']] = ['Paris','75008','France']
df.loc[425, ['city']] = ['Le Mans']
df.loc[431, ['city']] = ['Le Kremlin Bicêtre']
df.loc[436, ['city','postalCode', 'country']] = ['New-York','10018','USA']
df.loc[439, ['city','postalCode', 'country']] = ['Arcueil','94110','France']
df.loc[449, ['city']] = ['Le Kremlin Bicêtre']
df.loc[458, ['postalCode']] = ['75010']
df.loc[470:471, ['country']] = ['France']
df.loc[482, ['postalCode']] = ['75015']
df.loc[484, ['postalCode']] = ['75009']
df.loc[485, ['postalCode']] = ['75011']
df.loc[486, ['postalCode']] = ['75009']

df.loc[488, ['city','postalCode','country']] = ['Paris','75002','France']
df.loc[496, ['city','postalCode', 'country']] = ['Paris','75002','France']
df.loc[507, ['country']] = ['France']
df.loc[535, ['country']] = ['France']
df.loc[539, ['city','postalCode','country']] = ['Paris','75007','France']
df.loc[542, ['postalCode']] = ['75002']
df.loc[560, ['postalCode']] = ['France']
df.loc[565, ['postalCode']] = ['75018']
df.loc[570, ['country']] = ['France']

df.loc[573, ['city','postalCode']] = ['Le Perreux-sur-Marne','94170']
df.loc[575, ['country']] = ['France']
df.loc[579, ['city','postalCode','country']] = ['Paris','75009','France']
df.loc[583, ['country']] = ['France']
df.loc[604, ['country']] = ['France']
df.loc[606, ['country']] = ['France']
df.loc[607, ['postalCode']] = ['75010']
df.loc[609:610, ['postalCode']] = ['75010']
df.loc[612:613, ['country']] = ['France']
df.loc[653, ['country']] = ['France']
df.loc[655, ['country']] = ['France']
df.loc[662, ['country']] = ['Allemagne']
df.loc[672, ['city','postalCode','country']] = ['Paris','75012','France']
df.loc[703, ['country']] = ['France']
df.loc[720, ['city','postalCode','country']] = ['Marseille','13001','France']
df.loc[725, ['city','postalCode','country']] = ['Saint-Tropez','83990','France']
df.loc[766, ['city','postalCode','country']] = ['Paris','75010','France']
df.loc[773, ['city','postalCode','country']] = ['Lille','59800','France']

In [43]:
df.loc[152, ['postalCode']] = ['75010']
df.loc[182, ['postalCode']] = ['75011']
df.loc[236, ['postalCode']] = ['75002']
df.loc[300, ['postalCode']] = ['75003']
df.loc[391, ['postalCode']] = ['75004']
df.loc[477, ['postalCode']] = ['75013']

In [44]:
df.loc[444, 'country'] = 'France'
df.loc[560, 'country'] = 'France'

In [47]:
df.to_parquet('addresses-notebook_clean.parquet')

In [48]:
df.to_csv('addresses-notebook.csv', index=False)